const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const app = express(); app.use(cors()); app.use(express.json());
const PORT=process.env.PORT||3001, MONGODB_URI=process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/ucd_sih26129';const SSO_SECRET=process.env.SSO_SECRET||'ucd-sih26129-dev-sso-secret';
function requireSsoToken(req,res,next){const auth=req.headers.authorization||'',token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return res.status(401).json({error:'SSO token required'});try{req.identity=jwt.verify(token,SSO_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired SSO token'})}}
const STAGES=['Submitted','Under Review','Verification','Decision'];
const Application=mongoose.model('LicenseApplication',new mongoose.Schema({applicationId:{type:String,unique:true},citizenId:String,ownerName:String,currentStage:Number,applicationType:String,estCompletion:String,documentUrl:String,remarks:String,createdAt:Date,updatedAt:Date},{collection:'license_applications'}));
function validName(v){return typeof v==='string'&&/^[A-Za-z][A-Za-z .'-]{1,79}$/.test(v.trim())}
async function seed(){const rows=[['LIC-123','123',2,'Rahul Sharma','Trade License','2026-09-18','2026-09-09T10:00:00Z'],['LIC-124','124',1,'Priya Patel','Trade License','2026-09-25','2026-09-08T12:00:00Z'],['LIC-125','125',3,'Amit Shah','Trade License','2026-09-10','2026-09-07T09:00:00Z']];for(const [applicationId,citizenId,currentStage,ownerName,applicationType,estCompletion,updatedAt] of rows)await Application.updateOne({applicationId},{$setOnInsert:{applicationId,citizenId,currentStage,ownerName,applicationType,estCompletion,createdAt:new Date(updatedAt),updatedAt:new Date(updatedAt)}},{upsert:true})}
app.get('/api/license/status/:id',async(req,res)=>{const r=await Application.findOne({citizenId:String(req.params.id)}).sort({updatedAt:-1}).lean();if(!r)return res.status(404).json({error:'License ID not found'});res.json({department:'License Dept',stages:STAGES,...r})});
app.get('/api/license/applications',async(req,res)=>res.json({applications:(await Application.find().sort({updatedAt:-1}).lean()).map(r=>({department:'License Dept',...r}))}));
app.post('/api/license/apply',requireSsoToken,async(req,res)=>{const {citizenId,ownerName,applicationType,documentUrl,remarks}=req.body;if(!/^\d{3,12}$/.test(String(citizenId||'')))return res.status(400).json({error:'A valid citizenId is required'});if(!validName(ownerName))return res.status(400).json({error:'Enter a valid owner name'});if(!applicationType||applicationType.trim().length<2)return res.status(400).json({error:'applicationType is required'});const applicationId=`LIC-${Date.now().toString().slice(-8)}`,now=new Date();await Application.create({applicationId,citizenId:String(citizenId),currentStage:0,ownerName:ownerName.trim(),applicationType:applicationType.trim(),estCompletion:'TBD',documentUrl:documentUrl||null,remarks:remarks?String(remarks).trim().slice(0,500):'',createdAt:now,updatedAt:now});res.status(201).json({message:'Application submitted successfully',applicationId,department:'License Dept',currentStage:0})});
app.patch('/api/license/applications/:applicationId/stage',requireSsoToken,async(req,res)=>{const stage=Number(req.body.stage),r=await Application.findOne({applicationId:req.params.applicationId});if(!r)return res.status(404).json({error:'License application not found'});if(!Number.isInteger(stage)||stage<0||stage>=STAGES.length)return res.status(400).json({error:'Invalid stage'});const previousStage=r.currentStage;r.currentStage=stage;r.updatedAt=new Date();await r.save();res.json({message:'Stage updated',applicationId:r.applicationId,previousStage,currentStage:stage})});
app.get('/api/health',async(req,res)=>res.json({service:'license',status:mongoose.connection.readyState===1?'ok':'degraded',database:'mongodb'}));
mongoose.connect(MONGODB_URI).then(seed).then(()=>app.listen(PORT,()=>console.log(`License service running on port ${PORT} | MongoDB connected`))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
