const express=require('express'),axios=require('axios'),cors=require('cors'),crypto=require('crypto'),mongoose=require('mongoose'),multer=require('multer'),fs=require('fs'),path=require('path'),jwt=require('jsonwebtoken');
const app=express();app.use(cors());app.use(express.json());
const SSO_SECRET=process.env.SSO_SECRET||'ucd-sih26129-dev-sso-secret';
const cloudinary=require('cloudinary').v2;
const {CloudinaryStorage}=require('multer-storage-cloudinary');
cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
const upload=multer({storage:new CloudinaryStorage({cloudinary,params:{folder:'ucd_sih26129_uploads',allowed_formats:['pdf','jpg','jpeg','png'],resource_type:'auto'}}),limits:{fileSize:5*1024*1024}});
const PORT=process.env.PORT||3000,MONGODB_URI=process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/ucd_sih26129';const SERVICES={license:process.env.LICENSE_SERVICE_URL||'http://localhost:3001',landRecords:process.env.LAND_SERVICE_URL||'http://localhost:3002',tax:process.env.TAX_SERVICE_URL||'http://localhost:3003'};const APPLY_ENDPOINTS={license:`${SERVICES.license}/api/license/apply`,landRecords:`${SERVICES.landRecords}/api/land/apply`,tax:`${SERVICES.tax}/api/tax/apply`};
const Citizen=mongoose.model('Citizen',new mongoose.Schema({citizenId:{type:String,unique:true},name:String},{collection:'citizens'}));
const Session=mongoose.model('Session',new mongoose.Schema({token:{type:String,unique:true},role:String,citizenId:String,issuedAt:Date,expiresAt:Date},{collection:'sessions'}));
const Event=mongoose.model('Event',new mongoose.Schema({eventId:String,type:String,timestamp:Date,payload:mongoose.Schema.Types.Mixed},{collection:'events'}));
const Audit=mongoose.model('Audit',new mongoose.Schema({auditId:String,action:String,timestamp:Date,payload:mongoose.Schema.Types.Mixed},{collection:'audit_logs'}));
const Notification=mongoose.model('Notification',new mongoose.Schema({notificationId:String,citizenId:String,message:String,applicationId:String,timestamp:Date,read:Boolean},{collection:'notifications'}));
const Workflow=mongoose.model('Workflow',new mongoose.Schema({department:{type:String,unique:true},stages:[String],updatedAt:Date},{collection:'workflows'}));
const DEFAULT_WORKFLOWS={license:['Submitted','Under Review','Verification','Decision'],landRecords:['Submitted','Survey Verification','Officer Review','Decision'],tax:['Submitted','Under Review','Assessment','Decision']};
function validCitizenId(id){return /^\d{3,12}$/.test(String(id||'').trim())}function validName(n){return typeof n==='string'&&/^[A-Za-z][A-Za-z .'-]{1,79}$/.test(n.trim())}
async function getWorkflows(){const docs=await Workflow.find().lean();const out={...DEFAULT_WORKFLOWS};docs.forEach(d=>out[d.department]=d.stages);return out}
async function recordEvent(type,payload){return Event.create({eventId:crypto.randomUUID(),type,timestamp:new Date(),payload})}
async function recordAudit(action,payload={}){return Audit.create({auditId:crypto.randomUUID(),action,timestamp:new Date(),payload})}
async function notifyCitizen(citizenId,message,applicationId=null){return Notification.create({notificationId:crypto.randomUUID(),citizenId:String(citizenId),message,applicationId,timestamp:new Date(),read:false})}
async function requireSession(req,res,next){const auth=req.headers.authorization||'',token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return res.status(401).json({error:'Valid login session required'});let ssoPayload;try{ssoPayload=jwt.verify(token,SSO_SECRET)}catch{return res.status(401).json({error:'Valid login session required'})}const session=await Session.findOne({token,expiresAt:{$gt:new Date()}}).lean();if(!session)return res.status(401).json({error:'Valid login session required'});req.session={...session,...ssoPayload};next()}
function requireOfficer(req,res,next){if(req.session?.role!=='officer')return res.status(403).json({error:'Officer access required'});next()}
async function normalizeApplication(department,item){const workflows=await getWorkflows();const stages=workflows[department]||item.stages||[];return {...item,department,stages,currentStage:Math.min(item.currentStage||0,stages.length-1)}}
app.post('/api/auth/login',async(req,res)=>{const {role,citizenId}=req.body;if(!['citizen','officer'].includes(role))return res.status(400).json({error:'Role must be citizen or officer'});let citizen=null;if(role==='citizen'){if(!validCitizenId(citizenId))return res.status(400).json({error:'Citizen ID must contain 3–12 digits'});citizen=await Citizen.findOne({citizenId:String(citizenId)}).lean();if(!citizen)return res.status(404).json({error:'Citizen profile not found in master data'})}const identityId=role==='citizen'?String(citizenId):'officer';const token=jwt.sign({role,citizenId:role==='citizen'?String(citizenId):null,sub:identityId,iss:'ucd-gateway-sso'},SSO_SECRET,{expiresIn:'8h'});await Session.create({token,role,citizenId:role==='citizen'?String(citizenId):null,issuedAt:new Date(),expiresAt:new Date(Date.now()+8*60*60*1000)});await recordAudit('LOGIN',{role,citizenId:role==='citizen'?String(citizenId):null});await recordAudit('SSO_TOKEN_ISSUED',{role,identityId});res.json({token,role,citizen})});
app.get('/api/auth/whoami',requireSession,(req,res)=>res.json({role:req.session.role,citizenId:req.session.citizenId,sub:req.session.sub,issuer:req.session.iss,issuedAt:req.session.issuedAt,expiresAt:req.session.expiresAt}));
app.post('/api/auth/logout',requireSession,async(req,res)=>{await Session.deleteOne({token:req.headers.authorization.slice(7)});res.json({message:'Logged out'})});
app.post('/api/citizen/upload',requireSession,(req,res)=>{if(req.session.role!=='citizen')return res.status(403).json({error:'Citizen session required'});upload.single('document')(req,res,async err=>{if(err)return res.status(400).json({error:err.message||'Upload failed'});if(!req.file)return res.status(400).json({error:'No file uploaded'});const documentUrl=req.file.path;await recordAudit('DOCUMENT_UPLOADED',{citizenId:req.session.citizenId,originalName:req.file.originalname,documentUrl});res.status(201).json({documentUrl,originalName:req.file.originalname})})});app.get('/api/citizen/:id/dashboard',requireSession,async(req,res)=>{const id=String(req.params.id);if(!validCitizenId(id))return res.status(400).json({error:'Invalid Citizen ID'});if(req.session.role==='citizen'&&req.session.citizenId!==id)return res.status(403).json({error:'Citizens can only access their own applications'});const citizen=await Citizen.findOne({citizenId:id}).lean();const results=await Promise.allSettled([axios.get(`${SERVICES.license}/api/license/status/${id}`),axios.get(`${SERVICES.landRecords}/api/land/status/${id}`),axios.get(`${SERVICES.tax}/api/tax/status/${id}`)]);const services={};const names=['license','landRecords','tax'];for(let i=0;i<results.length;i++)if(results[i].status==='fulfilled')services[names[i]]=await normalizeApplication(names[i],results[i].value.data);res.json({citizen:citizen||{citizenId:id},citizenId:id,services})});
app.post('/api/citizen/apply',requireSession,async(req,res)=>{const {department,citizenId,ownerName,...formData}=req.body;if(req.session.role!=='citizen')return res.status(403).json({error:'Citizen session required'});if(String(citizenId)!==String(req.session.citizenId))return res.status(403).json({error:'Citizen ID does not match the logged-in session'});if(!await Citizen.exists({citizenId:String(citizenId)}))return res.status(404).json({error:'Citizen profile not found'});if(!APPLY_ENDPOINTS[department])return res.status(400).json({error:'Invalid department specified'});if(!validName(ownerName))return res.status(400).json({error:'Enter a valid owner name (letters and spaces only)'});try{const r=await axios.post(APPLY_ENDPOINTS[department],{citizenId:String(citizenId),ownerName:ownerName.trim(),...formData},{headers:{Authorization:req.headers.authorization}});const applicationId=r.data.applicationId;await recordEvent('APPLICATION_SUBMITTED',{citizenId:String(citizenId),department,applicationId});await recordAudit('APPLICATION_SUBMITTED',{citizenId:String(citizenId),department,applicationId});await notifyCitizen(citizenId,`Your ${department==='landRecords'?'Land Records':department==='license'?'License':'Tax & Revenue'} application ${applicationId} was submitted.`,applicationId);res.status(201).json(r.data)}catch(e){res.status(e.response?.status||500).json({error:e.response?.data?.error||'Failed to submit application',details:e.response?.data?.details||e.message})}});
app.get('/api/officer/applications',requireSession,requireOfficer,async(req,res)=>{const results=await Promise.allSettled([axios.get(`${SERVICES.license}/api/license/applications`),axios.get(`${SERVICES.landRecords}/api/land/applications`),axios.get(`${SERVICES.tax}/api/tax/applications`)]);const names=['license','landRecords','tax'],applications=[];for(let i=0;i<results.length;i++)if(results[i].status==='fulfilled')for(const a of results[i].value.data.applications)applications.push(await normalizeApplication(names[i],a));applications.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));res.json({applications})});
app.patch('/api/officer/applications/:department/:applicationId/stage',requireSession,requireOfficer,async(req,res)=>{const {department,applicationId}=req.params,stage=Number(req.body.stage),workflows=await getWorkflows();if(!SERVICES[department])return res.status(400).json({error:'Invalid department'});if(!Number.isInteger(stage)||stage<0||stage>=workflows[department].length)return res.status(400).json({error:'Invalid workflow stage'});const prefix=department==='license'?'license':department==='landRecords'?'land':'tax';try{const r=await axios.patch(`${SERVICES[department]}/api/${prefix}/applications/${applicationId}/stage`,{stage},{headers:{Authorization:req.headers.authorization}});const oldStage=r.data.previousStage??null,newStage=r.data.currentStage;await recordEvent('APPLICATION_STAGE_CHANGED',{role:'officer',department,applicationId,previousStage:oldStage,currentStage:newStage});await recordAudit('APPLICATION_STAGE_CHANGED',{role:'officer',department,applicationId,previousStage:oldStage,currentStage:newStage});try{const lr=await axios.get(`${SERVICES[department]}/api/${prefix}/applications`),target=(lr.data.applications||[]).find(a=>a.applicationId===applicationId);if(target)await notifyCitizen(target.citizenId,`Your application ${applicationId} moved to ${workflows[department][newStage]||'a new stage'}.`,applicationId)}catch(_){}res.json({...r.data,stages:workflows[department]})}catch(e){res.status(e.response?.status||500).json({error:e.response?.data?.error||'Failed to update application stage'})}});
app.get('/api/officer/stats',requireSession,requireOfficer,async(req,res)=>{const workflows=await getWorkflows(),results=await Promise.allSettled([axios.get(`${SERVICES.license}/api/license/applications`),axios.get(`${SERVICES.landRecords}/api/land/applications`),axios.get(`${SERVICES.tax}/api/tax/applications`)]),groups=[['license',results[0]],['landRecords',results[1]],['tax',results[2]]],byDepartment={},byStage={};let total=0;for(const [d,r] of groups){const apps=r.status==='fulfilled'?r.value.data.applications:[];byDepartment[d]=apps.length;total+=apps.length;for(const a of apps){const s=workflows[d][a.currentStage]||'Unknown';byStage[s]=(byStage[s]||0)+1}}res.json({total,byDepartment,byStage,workflows})});
app.get('/api/master/citizens/:id',requireSession,async(req,res)=>{if(req.session.role==='citizen'&&req.session.citizenId!==req.params.id)return res.status(403).json({error:'Access denied'});const c=await Citizen.findOne({citizenId:req.params.id}).lean();if(!c)return res.status(404).json({error:'Citizen profile not found'});res.json(c)});app.get('/api/master/citizens',requireSession,requireOfficer,async(req,res)=>res.json({citizens:await Citizen.find().sort({citizenId:1}).lean()}));
app.get('/api/workflows',requireSession,async(req,res)=>res.json({workflows:await getWorkflows()}));app.put('/api/workflows/:department',requireSession,requireOfficer,async(req,res)=>{const {department}=req.params,workflows=await getWorkflows(),stages=req.body.stages;if(!workflows[department])return res.status(400).json({error:'Invalid department'});if(!Array.isArray(stages)||stages.length<2||stages.length>8||stages.some(s=>typeof s!=='string'||!s.trim()))return res.status(400).json({error:'Provide 2–8 non-empty workflow stages'});const clean=stages.map(s=>s.trim());await Workflow.updateOne({department},{$set:{stages:clean,updatedAt:new Date()}},{upsert:true});await recordAudit('WORKFLOW_UPDATED',{department,stages:clean});res.json({message:'Workflow saved',department,stages:clean})});
app.get('/api/citizen/:id/notifications',requireSession,async(req,res)=>{const id=String(req.params.id);if(req.session.role==='citizen'&&req.session.citizenId!==id)return res.status(403).json({error:'Access denied'});res.json({notifications:await Notification.find({citizenId:id}).sort({timestamp:-1}).limit(50).lean()})});app.post('/api/citizen/:id/notifications/read',requireSession,async(req,res)=>{const id=String(req.params.id);if(req.session.role==='citizen'&&req.session.citizenId!==id)return res.status(403).json({error:'Access denied'});await Notification.updateMany({citizenId:id},{$set:{read:true}});res.json({message:'Notifications marked as read'})});
app.get('/api/officer/events',requireSession,requireOfficer,async(req,res)=>res.json({events:await Event.find().sort({timestamp:-1}).limit(100).lean()}));app.get('/api/officer/audit',requireSession,requireOfficer,async(req,res)=>res.json({audit:await Audit.find().sort({timestamp:-1}).limit(100).lean()}));
app.get('/api/officer/health',requireSession,requireOfficer,async(req,res)=>{const checks=[['gateway',`http://localhost:${PORT}/api/health`],['license',`${SERVICES.license}/api/health`],['landRecords',`${SERVICES.landRecords}/api/health`],['tax',`${SERVICES.tax}/api/health`]],result={};await Promise.all(checks.map(async([n,u])=>{const s=Date.now();try{const r=await axios.get(u,{timeout:8000});result[n]={status:r.data?.status==='ok'?'online':'degraded',responseTimeMs:Date.now()-s,database:r.data?.database||undefined}}catch(e){result[n]={status:'offline',responseTimeMs:Date.now()-s,error:e.code||'UNAVAILABLE'}}}));res.json({services:result,checkedAt:new Date().toISOString()})});
app.get('/api/connectors',requireSession,async(req,res)=>res.json({connectors:[{name:'REST Connector',type:'modern',purpose:'Connect REST/JSON department APIs'},{name:'Legacy Land Adapter',type:'legacy',purpose:'Maps legacy field names into the common data model',endpoint:'/api/connectors/legacy-land/demo'},{name:'Database Adapter',type:'legacy',purpose:'Integration point for department databases'}]}));app.get('/api/connectors/legacy-land/demo',requireSession,async(req,res)=>{const legacy={CITIZEN_NO:'124',SURVEY_NO:'SN-7788',OWNER:'Priya Patel',STATUS_CODE:'RVW'};res.json({source:'Legacy Land Records System',legacy,normalized:{citizenId:legacy.CITIZEN_NO,surveyNumber:legacy.SURVEY_NO,ownerName:legacy.OWNER,status:legacy.STATUS_CODE==='RVW'?'Under Review':legacy.STATUS_CODE}})});
app.get('/api/health',(req,res)=>res.json({service:'gateway',status:mongoose.connection.readyState===1?'ok':'degraded',database:'mongodb'}));
async function seed(){for(const [citizenId,name] of [['123','Rahul Sharma'],['124','Priya Patel'],['125','Amit Shah']])await Citizen.updateOne({citizenId},{$setOnInsert:{citizenId,name}},{upsert:true});for(const [department,stages] of Object.entries(DEFAULT_WORKFLOWS))await Workflow.updateOne({department},{$setOnInsert:{department,stages,updatedAt:new Date()}},{upsert:true})}
mongoose.connect(MONGODB_URI).then(seed).then(()=>app.listen(PORT,()=>console.log(`Gateway running on port ${PORT} | MongoDB connected`))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});